default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: database # Use o nome do serviço do Docker Compose para o banco de dados
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: search_analytics_development
  host: localhost
  username: postgres
  password: search_analytics
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: search_analytics_test
  host: localhost
  username: postgres
  password: search_analytics
  port: 5432
