default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: search_analytics_development
  host: database_development
  username: postgres
  password: search_analytics
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: search_analytics_test
  host: database_test
  username: postgres
  password: search_analytics_test
  port: 5432
